touch t/API/auth_user.t
touch t/API/author_books.t
touch t/API/author_show.t
touch t/API/book_isbn_to_id.t
touch t/API/book_review_counts.t
touch t/API/book_show.t
touch t/API/book_show_by_isbn.t
touch t/API/book_title.t
touch t/API/comment_create.t
touch t/API/comment_list.t
touch t/API/events_list.t
touch t/API/fanship_create.t
touch t/API/fanship_destroy.t
touch t/API/fanship_show.t
touch t/API/followers_create.t
touch t/API/followers_destroy.t
touch t/API/friend_confirm_recommendation.t
touch t/API/friend_confirm_request.t
touch t/API/friend_requests.t
touch t/API/friends_create.t
touch t/API/group_join.t
touch t/API/group_list.t
touch t/API/group_members.t
touch t/API/group_search.t
touch t/API/group_show.t
touch t/API/list_book.t
touch t/API/notifications.t
touch t/API/owned_books_create.t
touch t/API/owned_books_list.t
touch t/API/owned_books_show.t
touch t/API/owned_books_update.t
touch t/API/quotes_create.t
touch t/API/rating_create.t
touch t/API/rating_destroy.t
touch t/API/read_statuses_show.t
touch t/API/recommendations_show.t
touch t/API/review_create.t
touch t/API/review_edit.t
touch t/API/reviews_list.t
touch t/API/review_recent_reviews.t
touch t/API/review_show.t
touch t/API/review_show_by_user_and_book.t
touch t/API/review_update.t
touch t/API/search_authors.t
touch t/API/search_books.t
touch t/API/series_show.t
touch t/API/series_list.t
touch t/API/series_work.t
touch t/API/shelves_add_to_shelf.t
touch t/API/shelves_add_books_to_shelves.t
touch t/API/shelves_list.t
touch t/API/topic_create.t
touch t/API/topic_group_folder.t
touch t/API/topic_show.t
touch t/API/topic_unread_group.t
touch t/API/updates_friends.t
touch t/API/user_shelves_create.t
touch t/API/user_shelves_update.t
touch t/API/user_show.t
touch t/API/user_compare.t
touch t/API/user_followers.t
touch t/API/user_following.t
touch t/API/user_friends.t
touch t/API/user_status_create.t
touch t/API/user_status_destroy.t
touch t/API/user_status_show.t
touch t/API/user_status_index.t
touch t/API/work_editions.t